"""Add Phase 2 models: Tareas, Personal, RegistroHoras, Notificaciones

Revision ID: 0cf6fc4bab90
Revises: f9ce33c9d808
Create Date: 2025-11-09 15:55:40.401277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf6fc4bab90'
down_revision: Union[str, None] = 'f9ce33c9d808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
