"""initial_migration_with_all_models

Revision ID: f9ce33c9d808
Revises: 
Create Date: 2025-11-07 15:40:36.946672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ce33c9d808'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento_identidad', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('tarifa_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_empleado_activo_cargo', 'empleados', ['activo', 'cargo'], unique=False)
    op.create_index('idx_empleado_nombre_completo', 'empleados', ['nombre', 'apellido'], unique=False)
    op.create_index(op.f('ix_empleados_activo'), 'empleados', ['activo'], unique=False)
    op.create_index(op.f('ix_empleados_cargo'), 'empleados', ['cargo'], unique=False)
    op.create_index(op.f('ix_empleados_documento_identidad'), 'empleados', ['documento_identidad'], unique=True)
    op.create_index(op.f('ix_empleados_usuario_id'), 'empleados', ['usuario_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('leida_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_creado', 'notificaciones', ['creado_en'], unique=False)
    op.create_index('idx_notif_usuario_leida', 'notificaciones', ['usuario_id', 'leida'], unique=False)
    op.create_index('idx_notif_usuario_tipo', 'notificaciones', ['usuario_id', 'tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=False),
    sa.Column('asignado_a_id', sa.String(length=36), nullable=True),
    sa.Column('creado_por_id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tarea_asignado_estado', 'tareas', ['asignado_a_id', 'estado'], unique=False)
    op.create_index('idx_tarea_proyecto_estado', 'tareas', ['proyecto_id', 'estado'], unique=False)
    op.create_index('idx_tarea_vencimiento', 'tareas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_tareas_asignado_a_id'), 'tareas', ['asignado_a_id'], unique=False)
    op.create_index(op.f('ix_tareas_creado_por_id'), 'tareas', ['creado_por_id'], unique=False)
    op.create_index(op.f('ix_tareas_estado'), 'tareas', ['estado'], unique=False)
    op.create_index(op.f('ix_tareas_prioridad'), 'tareas', ['prioridad'], unique=False)
    op.create_index(op.f('ix_tareas_proyecto_id'), 'tareas', ['proyecto_id'], unique=False)
    op.create_table('registros_horas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empleado_id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=False),
    sa.Column('tarea_id', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registro_empleado_fecha', 'registros_horas', ['empleado_id', 'fecha'], unique=False)
    op.create_index('idx_registro_empleado_proyecto', 'registros_horas', ['empleado_id', 'proyecto_id'], unique=False)
    op.create_index('idx_registro_proyecto_fecha', 'registros_horas', ['proyecto_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_registros_horas_empleado_id'), 'registros_horas', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_registros_horas_fecha'), 'registros_horas', ['fecha'], unique=False)
    op.create_index(op.f('ix_registros_horas_proyecto_id'), 'registros_horas', ['proyecto_id'], unique=False)
    op.create_index(op.f('ix_registros_horas_tarea_id'), 'registros_horas', ['tarea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_horas_tarea_id'), table_name='registros_horas')
    op.drop_index(op.f('ix_registros_horas_proyecto_id'), table_name='registros_horas')
    op.drop_index(op.f('ix_registros_horas_fecha'), table_name='registros_horas')
    op.drop_index(op.f('ix_registros_horas_empleado_id'), table_name='registros_horas')
    op.drop_index('idx_registro_proyecto_fecha', table_name='registros_horas')
    op.drop_index('idx_registro_empleado_proyecto', table_name='registros_horas')
    op.drop_index('idx_registro_empleado_fecha', table_name='registros_horas')
    op.drop_table('registros_horas')
    op.drop_index(op.f('ix_tareas_proyecto_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_prioridad'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_estado'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_creado_por_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_asignado_a_id'), table_name='tareas')
    op.drop_index('idx_tarea_vencimiento', table_name='tareas')
    op.drop_index('idx_tarea_proyecto_estado', table_name='tareas')
    op.drop_index('idx_tarea_asignado_estado', table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index('idx_notif_usuario_tipo', table_name='notificaciones')
    op.drop_index('idx_notif_usuario_leida', table_name='notificaciones')
    op.drop_index('idx_notif_creado', table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_empleados_usuario_id'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_documento_identidad'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_cargo'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_activo'), table_name='empleados')
    op.drop_index('idx_empleado_nombre_completo', table_name='empleados')
    op.drop_index('idx_empleado_activo_cargo', table_name='empleados')
    op.drop_table('empleados')
    # ### end Alembic commands ###
